# Site settings
name: Armand Ballaci
email: aballaci@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, JEE, Spring, Apache Kafka, Angular, React, Confluent, Flutter, Agile, Full Stack Entwickler Nürnberg"
skills: "Senior Software Engineer in Nürnberg"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ballaci/
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7aa8cc
  primary-rgb: "33, 150, 243"
  secondary: 206faf
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
